package com.xoyar.cms.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_area.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Area implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** parent_id. */
	private Integer parentId;

	/** name. */
	private String name;

	/** sort. */
	private Integer sort;

	/** code. */
	private String code;

	/** update_by. */
	private String updateBy;

	/** update_date. */
	private Date updateDate;

	/** remarks. */
	private String remarks;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "Area [id=" + id + ", parentId=" + parentId + ", name=" + name + ", sort=" + sort + ", code=" + code
				+ ", updateBy=" + updateBy + ", updateDate=" + updateDate + ", remarks=" + remarks + "]";
	}



}
