package com.xoyar.cms.entity;

import com.xoyar.cms.dto.TreeDto;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of pm_sys_menu.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Menu extends TreeDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** parentName. */
	private String parentName;

	/** sort. */
	private Integer sort;

	/** href. */
	private String href;

	/** target. */
	private String target;

	/** icon. */
	private String icon;

	/** is_show. */
	private String isShow;

	/** permission. */
	private String permission;

	/** update_by. */
	private String updateBy;

	/** update_date. */
	private Date updateDate;

	/** remarks. */
	private String remarks;

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getHref() {
		return href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	public String getTarget() {
		return target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getIsShow() {
		return isShow;
	}

	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	public String getPermission() {
		return permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "Menu{" +
				"parentName='" + parentName + '\'' +
				", sort=" + sort +
				", href='" + href + '\'' +
				", target='" + target + '\'' +
				", icon='" + icon + '\'' +
				", isShow='" + isShow + '\'' +
				", permission='" + permission + '\'' +
				", updateBy='" + updateBy + '\'' +
				", updateDate=" + updateDate +
				", remarks='" + remarks + '\'' +
				'}';
	}
}
