package com.xoyar.cms.entity;

/**
 * Model class of pm_sys_role_dept.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoleToDept{

	private Integer roleId;
	
	private Integer deptId;

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getDeptId() {
		return deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}
}
