package com.xoyar.cms.entity;

/**
 * Model class of pm_sys_role_area.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoleToArea{

	private Integer roleId;
	
	private Integer areaId;

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getAreaId() {
		return areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

}
