package com.xoyar.cms.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of pm_sys_user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_id. */
	private Integer userId;

	/** dept_id. */
	private Integer deptId;

	/** login_name. */
	private String loginName;

	/** password. */
	private String password;

	/** user_no. */
	private String userNo;

	/** user_name. */
	private String userName;

	/** email. */
	private String email;

	/** phone. */
	private String phone;

	/** mobile. */
	private String mobile;

	/** update_by. */
	private String updateBy;

	/** update_date. */
	private Date updateDate;

	/** remarks. */
	private String remarks;

	/**
	 * 角色idList
	 */
	private Integer[] roleIdList;

	public Integer[] getRoleIdList() {
		return roleIdList;
	}

	public void setRoleIdList(Integer[] roleIdList) {
		this.roleIdList = roleIdList;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getDeptId() {
		return deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", deptId=" + deptId + ", loginName=" + loginName + ", password=" + password
				+ ", userNo=" + userNo + ", userName=" + userName + ", email=" + email + ", phone=" + phone
				+ ", mobile=" + mobile + ", updateBy=" + updateBy + ", updateDate=" + updateDate + ", remarks="
				+ remarks + "]";
	}

	
}
