package com.xoyar.cms.entity;

/**
 * Model class of pm_sys_user_role.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserToRole {

	private Integer userId;
	
	private Integer roleId;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
